name: chat
services:
  service:
    build:
      context: .
    restart: on-failure
    mem_limit: 256m
    mem_reservation: 128m
    ports:
      - 8082:8082
    environment:
      # This environment variable accepts values between 0 and 1 (inclusive) to 
      # define the chance for the service to return an HTTP status 500 - Internal server error.
      - RESPONSE_ERROR_RATIO=0
