server:
  port: ${PORT:8081}
spring:
  application.name: chat
  webflux.base-path: ${spring.application.name}
chat:
  mongo:
    schema: mongodb
    host: ${MONGO_HOST:localhost}
    port: 27018
    username: root
    password: example
    database: chat
    authSource: admin
  response-error-ratio: ${RESPONSE_ERROR_RATIO:0}